//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsText { get; set; }
        public string HtmlDisplayItemFormat { get; set; }
        public string HtmlDisplayOuterFormat { get; set; }
        public string HtmlDisplayWrapperFormat { get; set; }
    }
}
